const express=require('express')
const app=express()
const {login}=require('./controller/login')
const cors=require('cors')
app.use(cors())
const body_parser=require('body-parser')
const stripe=require('stripe')(
    "sk_test_51OK7pRSIOJiY1NziL2RChC31nzVTivbE9JO0pTlAkVsqUgXBswHtBNcTHkQCAm1wr2MZdjPUYc7g7yvWAJTJbyGj00ceYgNfjU"
    );
const {v4:uuidv4}=require('uuid')
const {signup}=require('./controller/signup')
const PORT=process.env.PORT || 5000;
const {Addtocart,cart,cartRemove,orderDetails}=require('./controller/cart')
const cookie_parser=require('cookie-parser')
const {homepage,mobiles,products}=require('./controller/shoppingapp')
app.use(express.json())
app.use(body_parser.urlencoded({extended:true}))
app.use(express.urlencoded({extended:false}))
app.use(cookie_parser())
app.get('/homepage',homepage)
app.get('/',(req,res)=>{res.send("hello")})
app.get('/mobile',mobiles)
app.get('/fashion',mobiles)
app.post('/login',login)
app.post('/signup',signup)
app.get('/laptop',mobiles)
app.get('/furniture',mobiles)
app.get('/toys',mobiles)
app.get('/Addtocart',Addtocart)
app.post('/cart',cart)
app.post('/cart/remove',cartRemove)
app.post('/orderDetails',orderDetails)
app.get('/mobile/products',products)
app.get('/toys/products',products)
app.get('/laptop/products',products)
app.get('/fashion/products',products)
app.get('/furniture/products',products)
app.post('/payment',(req,res)=>{
    res.status(200).send('ok')
})
app.listen(PORT,()=>console.log("port is:",PORT))